-- MySQL Script generated by MySQL Workbench
-- Sun Mar 18 15:18:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBXMarksTheSpot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DBXMarksTheSpot` ;

-- -----------------------------------------------------
-- Schema DBXMarksTheSpot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBXMarksTheSpot` DEFAULT CHARACTER SET utf8 ;
USE `DBXMarksTheSpot` ;

-- -----------------------------------------------------
-- Table `DBXMarksTheSpot`.`UsersDB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBXMarksTheSpot`.`UsersDB` ;

CREATE TABLE IF NOT EXISTS `DBXMarksTheSpot`.`UsersDB` (
  `Name` TINYTEXT NOT NULL,
  `Email Address` TINYTEXT NOT NULL,
  `Password` TINYTEXT NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;

CREATE FULLTEXT INDEX `Name` ON `DBXMarksTheSpot`.`UsersDB` (`Name` ASC, `Password` ASC, `Email Address` ASC);

CREATE UNIQUE INDEX `Email` ON `DBXMarksTheSpot`.`UsersDB` (`Email Address` ASC);

CREATE UNIQUE INDEX `UserID_UNIQUE` ON `DBXMarksTheSpot`.`UsersDB` (`UserID` ASC);


-- -----------------------------------------------------
-- Table `DBXMarksTheSpot`.`Building`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBXMarksTheSpot`.`Building` ;

CREATE TABLE IF NOT EXISTS `DBXMarksTheSpot`.`Building` (
  `BuildingName` TINYTEXT NOT NULL,
  `BuildingID` INT NOT NULL,
  PRIMARY KEY (`BuildingID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `BuildingID_UNIQUE` ON `DBXMarksTheSpot`.`Building` (`BuildingID` ASC);


-- -----------------------------------------------------
-- Table `DBXMarksTheSpot`.`Floor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBXMarksTheSpot`.`Floor` ;

CREATE TABLE IF NOT EXISTS `DBXMarksTheSpot`.`Floor` (
  `BuildingID` INT NOT NULL,
  `FloorID` INT NOT NULL,
  `FloorNumber` INT NOT NULL,
  PRIMARY KEY (`FloorID`),
  CONSTRAINT `BuildingID`
    FOREIGN KEY (`BuildingID`)
    REFERENCES `DBXMarksTheSpot`.`Building` (`BuildingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `FloorID_UNIQUE` ON `DBXMarksTheSpot`.`Floor` (`FloorID` ASC);

CREATE INDEX `BuildingID_idx` ON `DBXMarksTheSpot`.`Floor` (`BuildingID` ASC);


-- -----------------------------------------------------
-- Table `DBXMarksTheSpot`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBXMarksTheSpot`.`Room` ;

CREATE TABLE IF NOT EXISTS `DBXMarksTheSpot`.`Room` (
  `FloorID` INT NOT NULL,
  `RoomID` INT NOT NULL,
  `RoomNumber` INT NOT NULL,
  `BuildingID` INT NOT NULL,
  PRIMARY KEY (`RoomID`),
  CONSTRAINT `FloorID`
    FOREIGN KEY (`FloorID`)
    REFERENCES `DBXMarksTheSpot`.`Floor` (`FloorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BuildingID`
    FOREIGN KEY (`BuildingID`)
    REFERENCES `DBXMarksTheSpot`.`Building` (`BuildingID`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FloorID_idx` ON `DBXMarksTheSpot`.`Room` (`FloorID` ASC);

CREATE INDEX `BuildingID_idx` ON `DBXMarksTheSpot`.`Room` (`BuildingID` ASC);


-- -----------------------------------------------------
-- Table `DBXMarksTheSpot`.`Monday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBXMarksTheSpot`.`Monday` ;

CREATE TABLE IF NOT EXISTS `DBXMarksTheSpot`.`Monday` (
  `idMonday` INT NOT NULL,
  `RoomID` INT NOT NULL,
  `08:00a.m.-09:00a.m.` INT NOT NULL DEFAULT 0,
  `09:00a.m.-10:00a.m.` INT NOT NULL DEFAULT 0,
  `10:00a.m.-11:00a.m.` INT NOT NULL DEFAULT 0,
  `11:00a.m.-12:00p.m.` INT NOT NULL DEFAULT 0,
  `12:00p.m.-01:00p.m.` INT NOT NULL DEFAULT 0,
  `01:00p.m.-02:00p.m.` INT NOT NULL DEFAULT 0,
  `02:00p.m.-03:00p.m.` INT NOT NULL DEFAULT 0,
  `03:00p.m.-04:00p.m.` INT NOT NULL DEFAULT 0,
  `04:00p.m.-05:00p.m.` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idMonday`),
  CONSTRAINT `RoomID`
    FOREIGN KEY (`RoomID`)
    REFERENCES `DBXMarksTheSpot`.`Room` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idMonday_UNIQUE` ON `DBXMarksTheSpot`.`Monday` (`idMonday` ASC);

CREATE UNIQUE INDEX `RoomID_UNIQUE` ON `DBXMarksTheSpot`.`Monday` (`RoomID` ASC);


-- -----------------------------------------------------
-- Table `DBXMarksTheSpot`.`Tuesday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBXMarksTheSpot`.`Tuesday` ;

CREATE TABLE IF NOT EXISTS `DBXMarksTheSpot`.`Tuesday` (
  `idTuesday` INT NOT NULL,
  `RoomID` INT NOT NULL,
  `08:00a.m.-09:00a.m.` INT NOT NULL DEFAULT 0,
  `09:00a.m.-10:00a.m.` INT NOT NULL DEFAULT 0,
  `10:00a.m.-11:00a.m.` INT NOT NULL DEFAULT 0,
  `11:00a.m.-12:00p.m.` INT NOT NULL DEFAULT 0,
  `12:00p.m.-01:00p.m.` INT NOT NULL DEFAULT 0,
  `01:00p.m.-02:00p.m.` INT NOT NULL DEFAULT 0,
  `02:00p.m.-03:00p.m.` INT NOT NULL DEFAULT 0,
  `03:00p.m.-04:00p.m.` INT NOT NULL DEFAULT 0,
  `04:00p.m.-05:00p.m.` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idTuesday`),
  CONSTRAINT `RoomID`
    FOREIGN KEY (`RoomID`)
    REFERENCES `DBXMarksTheSpot`.`Room` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idMonday_UNIQUE` ON `DBXMarksTheSpot`.`Tuesday` (`idTuesday` ASC);

CREATE UNIQUE INDEX `RoomID_UNIQUE` ON `DBXMarksTheSpot`.`Tuesday` (`RoomID` ASC);


-- -----------------------------------------------------
-- Table `DBXMarksTheSpot`.`Wednesday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBXMarksTheSpot`.`Wednesday` ;

CREATE TABLE IF NOT EXISTS `DBXMarksTheSpot`.`Wednesday` (
  `idWednesday` INT NOT NULL,
  `RoomID` INT NOT NULL,
  `08:00a.m.-09:00a.m.` INT NOT NULL DEFAULT 0,
  `09:00a.m.-10:00a.m.` INT NOT NULL DEFAULT 0,
  `10:00a.m.-11:00a.m.` INT NOT NULL DEFAULT 0,
  `11:00a.m.-12:00p.m.` INT NOT NULL DEFAULT 0,
  `12:00p.m.-01:00p.m.` INT NOT NULL DEFAULT 0,
  `01:00p.m.-02:00p.m.` INT NOT NULL DEFAULT 0,
  `02:00p.m.-03:00p.m.` INT NOT NULL DEFAULT 0,
  `03:00p.m.-04:00p.m.` INT NOT NULL DEFAULT 0,
  `04:00p.m.-05:00p.m.` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idWednesday`),
  CONSTRAINT `RoomID`
    FOREIGN KEY (`RoomID`)
    REFERENCES `DBXMarksTheSpot`.`Room` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idMonday_UNIQUE` ON `DBXMarksTheSpot`.`Wednesday` (`idWednesday` ASC);

CREATE UNIQUE INDEX `RoomID_UNIQUE` ON `DBXMarksTheSpot`.`Wednesday` (`RoomID` ASC);


-- -----------------------------------------------------
-- Table `DBXMarksTheSpot`.`Thursday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBXMarksTheSpot`.`Thursday` ;

CREATE TABLE IF NOT EXISTS `DBXMarksTheSpot`.`Thursday` (
  `idThursday` INT NOT NULL,
  `RoomID` INT NOT NULL,
  `08:00a.m.-09:00a.m.` INT NOT NULL DEFAULT 0,
  `09:00a.m.-10:00a.m.` INT NOT NULL DEFAULT 0,
  `10:00a.m.-11:00a.m.` INT NOT NULL DEFAULT 0,
  `11:00a.m.-12:00p.m.` INT NOT NULL DEFAULT 0,
  `12:00p.m.-01:00p.m.` INT NOT NULL DEFAULT 0,
  `01:00p.m.-02:00p.m.` INT NOT NULL DEFAULT 0,
  `02:00p.m.-03:00p.m.` INT NOT NULL DEFAULT 0,
  `03:00p.m.-04:00p.m.` INT NOT NULL DEFAULT 0,
  `04:00p.m.-05:00p.m.` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idThursday`),
  CONSTRAINT `RoomID`
    FOREIGN KEY (`RoomID`)
    REFERENCES `DBXMarksTheSpot`.`Room` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idMonday_UNIQUE` ON `DBXMarksTheSpot`.`Thursday` (`idThursday` ASC);

CREATE UNIQUE INDEX `RoomID_UNIQUE` ON `DBXMarksTheSpot`.`Thursday` (`RoomID` ASC);


-- -----------------------------------------------------
-- Table `DBXMarksTheSpot`.`Friday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBXMarksTheSpot`.`Friday` ;

CREATE TABLE IF NOT EXISTS `DBXMarksTheSpot`.`Friday` (
  `idFriday` INT NOT NULL,
  `RoomID` INT NOT NULL,
  `08:00a.m.-09:00a.m.` INT NOT NULL DEFAULT 0,
  `09:00a.m.-10:00a.m.` INT NOT NULL DEFAULT 0,
  `10:00a.m.-11:00a.m.` INT NOT NULL DEFAULT 0,
  `11:00a.m.-12:00p.m.` INT NOT NULL DEFAULT 0,
  `12:00p.m.-01:00p.m.` INT NOT NULL DEFAULT 0,
  `01:00p.m.-02:00p.m.` INT NOT NULL DEFAULT 0,
  `02:00p.m.-03:00p.m.` INT NOT NULL DEFAULT 0,
  `03:00p.m.-04:00p.m.` INT NOT NULL DEFAULT 0,
  `04:00p.m.-05:00p.m.` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idFriday`),
  CONSTRAINT `RoomID`
    FOREIGN KEY (`RoomID`)
    REFERENCES `DBXMarksTheSpot`.`Room` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idMonday_UNIQUE` ON `DBXMarksTheSpot`.`Friday` (`idFriday` ASC);

CREATE UNIQUE INDEX `RoomID_UNIQUE` ON `DBXMarksTheSpot`.`Friday` (`RoomID` ASC);


-- -----------------------------------------------------
-- Table `DBXMarksTheSpot`.`Saturday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBXMarksTheSpot`.`Saturday` ;

CREATE TABLE IF NOT EXISTS `DBXMarksTheSpot`.`Saturday` (
  `idSaturday` INT NOT NULL,
  `RoomID` INT NOT NULL,
  `08:00a.m.-09:00a.m.` INT NOT NULL DEFAULT 0,
  `09:00a.m.-10:00a.m.` INT NOT NULL DEFAULT 0,
  `10:00a.m.-11:00a.m.` INT NOT NULL DEFAULT 0,
  `11:00a.m.-12:00p.m.` INT NOT NULL DEFAULT 0,
  `12:00p.m.-01:00p.m.` INT NOT NULL DEFAULT 0,
  `01:00p.m.-02:00p.m.` INT NOT NULL DEFAULT 0,
  `02:00p.m.-03:00p.m.` INT NOT NULL DEFAULT 0,
  `03:00p.m.-04:00p.m.` INT NOT NULL DEFAULT 0,
  `04:00p.m.-05:00p.m.` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idSaturday`),
  CONSTRAINT `RoomID`
    FOREIGN KEY (`RoomID`)
    REFERENCES `DBXMarksTheSpot`.`Room` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idMonday_UNIQUE` ON `DBXMarksTheSpot`.`Saturday` (`idSaturday` ASC);

CREATE UNIQUE INDEX `RoomID_UNIQUE` ON `DBXMarksTheSpot`.`Saturday` (`RoomID` ASC);


-- -----------------------------------------------------
-- Table `DBXMarksTheSpot`.`Sunday`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBXMarksTheSpot`.`Sunday` ;

CREATE TABLE IF NOT EXISTS `DBXMarksTheSpot`.`Sunday` (
  `idSunday` INT NOT NULL,
  `RoomID` INT NOT NULL,
  `08:00a.m.-09:00a.m.` INT NOT NULL DEFAULT 0,
  `09:00a.m.-10:00a.m.` INT NOT NULL DEFAULT 0,
  `10:00a.m.-11:00a.m.` INT NOT NULL DEFAULT 0,
  `11:00a.m.-12:00p.m.` INT NOT NULL DEFAULT 0,
  `12:00p.m.-01:00p.m.` INT NOT NULL DEFAULT 0,
  `01:00p.m.-02:00p.m.` INT NOT NULL DEFAULT 0,
  `02:00p.m.-03:00p.m.` INT NOT NULL DEFAULT 0,
  `03:00p.m.-04:00p.m.` INT NOT NULL DEFAULT 0,
  `04:00p.m.-05:00p.m.` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idSunday`),
  CONSTRAINT `RoomID`
    FOREIGN KEY (`RoomID`)
    REFERENCES `DBXMarksTheSpot`.`Room` (`RoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idMonday_UNIQUE` ON `DBXMarksTheSpot`.`Sunday` (`idSunday` ASC);

CREATE UNIQUE INDEX `RoomID_UNIQUE` ON `DBXMarksTheSpot`.`Sunday` (`RoomID` ASC);

SET SQL_MODE = '';
GRANT USAGE ON *.* TO Admin;
 DROP USER Admin;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'Admin' IDENTIFIED BY '1234';

GRANT ALL ON `DBXMarksTheSpot`.* TO 'Admin';
GRANT SELECT ON TABLE `DBXMarksTheSpot`.* TO 'Admin';
GRANT SELECT, INSERT, TRIGGER ON TABLE `DBXMarksTheSpot`.* TO 'Admin';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `DBXMarksTheSpot`.* TO 'Admin';
GRANT EXECUTE ON ROUTINE `DBXMarksTheSpot`.* TO 'Admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `DBXMarksTheSpot`.`UsersDB`
-- -----------------------------------------------------
START TRANSACTION;
USE `DBXMarksTheSpot`;
INSERT INTO `DBXMarksTheSpot`.`UsersDB` (`Name`, `Email Address`, `Password`, `UserID`) VALUES ('Santiago Salazar', 'salazars1@xavier.edu', '1234', DEFAULT);
INSERT INTO `DBXMarksTheSpot`.`UsersDB` (`Name`, `Email Address`, `Password`, `UserID`) VALUES ('Santiago Salazar 2', 'salazars1@xavier.edu', '1234', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `DBXMarksTheSpot`.`Building`
-- -----------------------------------------------------
START TRANSACTION;
USE `DBXMarksTheSpot`;
INSERT INTO `DBXMarksTheSpot`.`Building` (`BuildingName`, `BuildingID`) VALUES ('Alter Hall', 001);
INSERT INTO `DBXMarksTheSpot`.`Building` (`BuildingName`, `BuildingID`) VALUES ('HailStones', 002);
INSERT INTO `DBXMarksTheSpot`.`Building` (`BuildingName`, `BuildingID`) VALUES ('Smith', 003);
INSERT INTO `DBXMarksTheSpot`.`Building` (`BuildingName`, `BuildingID`) VALUES ('Linder', 004);
INSERT INTO `DBXMarksTheSpot`.`Building` (`BuildingName`, `BuildingID`) VALUES ('Cohen Center', 005);
INSERT INTO `DBXMarksTheSpot`.`Building` (`BuildingName`, `BuildingID`) VALUES ('Cintas Center', 006);
INSERT INTO `DBXMarksTheSpot`.`Building` (`BuildingName`, `BuildingID`) VALUES ('Hinkle', 007);
INSERT INTO `DBXMarksTheSpot`.`Building` (`BuildingName`, `BuildingID`) VALUES ('Albers', 008);
INSERT INTO `DBXMarksTheSpot`.`Building` (`BuildingName`, `BuildingID`) VALUES ('Logan Hall', 009);
INSERT INTO `DBXMarksTheSpot`.`Building` (`BuildingName`, `BuildingID`) VALUES ('Elet', 010);
INSERT INTO `DBXMarksTheSpot`.`Building` (`BuildingName`, `BuildingID`) VALUES ('CLC', 011);

COMMIT;


-- -----------------------------------------------------
-- Data for table `DBXMarksTheSpot`.`Floor`
-- -----------------------------------------------------
START TRANSACTION;
USE `DBXMarksTheSpot`;
INSERT INTO `DBXMarksTheSpot`.`Floor` (`BuildingID`, `FloorID`, `FloorNumber`) VALUES (001, 000, 0);
INSERT INTO `DBXMarksTheSpot`.`Floor` (`BuildingID`, `FloorID`, `FloorNumber`) VALUES (001, 001, 1);
INSERT INTO `DBXMarksTheSpot`.`Floor` (`BuildingID`, `FloorID`, `FloorNumber`) VALUES (001, 002, 2);
INSERT INTO `DBXMarksTheSpot`.`Floor` (`BuildingID`, `FloorID`, `FloorNumber`) VALUES (001, 003, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `DBXMarksTheSpot`.`Room`
-- -----------------------------------------------------
START TRANSACTION;
USE `DBXMarksTheSpot`;
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (000, 001, 001, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (000, 007, 007, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (000, 006, 006, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (000, 005, 005, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (000, 003, 003, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (000, 004, 004, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (001, 104, 104, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (001, 105, 105, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (001, 103, 103, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (001, 102, 102, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (001, 106, 106, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (001, 107, 107, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (001, 101, 101, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (001, 108, 108, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (001, 109, 109, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (002, 212, 212, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (002, 211, 211, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (002, 209, 209, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (002, 208, 208, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (002, 207, 207, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (002, 206, 206, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (002, 205, 205, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (002, 204, 204, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (002, 203, 203, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (003, 304, 304, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (003, 306, 306, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (003, 307, 307, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (003, 303, 303, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (003, 302, 302, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (003, 308, 308, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (003, 309, 309, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (003, 301, 301, 001);
INSERT INTO `DBXMarksTheSpot`.`Room` (`FloorID`, `RoomID`, `RoomNumber`, `BuildingID`) VALUES (003, 310, 310, 001);

COMMIT;


-- -----------------------------------------------------
-- Data for table `DBXMarksTheSpot`.`Monday`
-- -----------------------------------------------------
START TRANSACTION;
USE `DBXMarksTheSpot`;
INSERT INTO `DBXMarksTheSpot`.`Monday` (`idMonday`, `RoomID`, `08:00a.m.-09:00a.m.`, `09:00a.m.-10:00a.m.`, `10:00a.m.-11:00a.m.`, `11:00a.m.-12:00p.m.`, `12:00p.m.-01:00p.m.`, `01:00p.m.-02:00p.m.`, `02:00p.m.-03:00p.m.`, `03:00p.m.-04:00p.m.`, `04:00p.m.-05:00p.m.`) VALUES (100, 001, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `DBXMarksTheSpot`.`Monday` (`idMonday`, `RoomID`, `08:00a.m.-09:00a.m.`, `09:00a.m.-10:00a.m.`, `10:00a.m.-11:00a.m.`, `11:00a.m.-12:00p.m.`, `12:00p.m.-01:00p.m.`, `01:00p.m.-02:00p.m.`, `02:00p.m.-03:00p.m.`, `03:00p.m.-04:00p.m.`, `04:00p.m.-05:00p.m.`) VALUES (100, 002, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `DBXMarksTheSpot`.`Monday` (`idMonday`, `RoomID`, `08:00a.m.-09:00a.m.`, `09:00a.m.-10:00a.m.`, `10:00a.m.-11:00a.m.`, `11:00a.m.-12:00p.m.`, `12:00p.m.-01:00p.m.`, `01:00p.m.-02:00p.m.`, `02:00p.m.-03:00p.m.`, `03:00p.m.-04:00p.m.`, `04:00p.m.-05:00p.m.`) VALUES (100, 003, 0, 0, 0, 0, 0, 0, 0, 1, 0);
INSERT INTO `DBXMarksTheSpot`.`Monday` (`idMonday`, `RoomID`, `08:00a.m.-09:00a.m.`, `09:00a.m.-10:00a.m.`, `10:00a.m.-11:00a.m.`, `11:00a.m.-12:00p.m.`, `12:00p.m.-01:00p.m.`, `01:00p.m.-02:00p.m.`, `02:00p.m.-03:00p.m.`, `03:00p.m.-04:00p.m.`, `04:00p.m.-05:00p.m.`) VALUES (100, 004, 1, 1, 1, 0, 1, 0, 1, 0, 1);

COMMIT;

