# Generated by Django 2.0.3 on 2018-04-01 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='timeType',
        ),
    ]
