# Generated by Django 2.0.3 on 2018-04-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_room_testfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeInt', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.CalendarDay')),
            ],
        ),
        migrations.CreateModel(
            name='NewCalender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='testField',
        ),
        migrations.AddField(
            model_name='newcalender',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.Room'),
        ),
        migrations.AddField(
            model_name='calendarday',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.NewCalender'),
        ),
    ]
