# Generated by Django 2.0.3 on 2018-04-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_auto_20180403_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarday',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='calendartime',
            name='day',
        ),
        migrations.RemoveField(
            model_name='newcalender',
            name='room',
        ),
        migrations.DeleteModel(
            name='CalendarDay',
        ),
        migrations.DeleteModel(
            name='CalendarTime',
        ),
        migrations.DeleteModel(
            name='NewCalender',
        ),
    ]
