# Generated by Django 2.0.3 on 2018-04-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_auto_20180403_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checkedIn',
            field=models.BooleanField(default=False),
        ),
    ]
